name: flutter_js_bridger_example
description: Example demonstrating flutter_js_bridger usage.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_js_bridger:
    path: ../
