name: flutter_js_bridger
description: >-
  Universal JavaScript Bridge for Flutter & Dart — Use any npm package
  directly in your Flutter/Dart projects on any platform (Desktop, Web,
  iOS, Android). Seamlessly call JavaScript functions, access objects,
  and manage npm packages from Dart.
version: 2.0.0
homepage: https://github.com/eslam-reda-div/flutter_js_bridger
repository: https://github.com/eslam-reda-div/flutter_js_bridger
issue_tracker: https://github.com/eslam-reda-div/flutter_js_bridger/issues
topics:
  - javascript
  - npm
  - bridge
  - cross-platform
  - ffi

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  flutter_js_bridger: flutter_js_bridger

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
